### PR TITLE
Print real version both in mstpd and mstpctl

### PR DESCRIPTION
**Pull request by dvitas**
Resolves issue #12

### CODE REVIEW

**Comment by dvitas** [comment]
Workflow suggestion:
I don't think that we really need PRs for such a small changes. So I suggest the following:
 - keep the master branch more or less stable.
 - create "development" branch and push such a small changes to that branch directly. When we feel that code in the "development" branch is stable enough and has enough significant changes - we merge it ti the master branch and place new version tag.
 - Only lengthy or controversial changes should go in as PRs. Or changes from third parties.

Thoughts?

**Comment by vivien** [comment]
Hi Vitalii,

> Workflow suggestion:
> I don't think that we really need PRs for such a small changes. So I suggest the following:
> 
>    keep the master branch more or less stable.
>    create "development" branch and push such a small changes to that branch directly. When we feel that code in the "development" branch is stable enough and has enough significant changes - we merge it into the master branch and mark it with the new version tag.
>    Only lengthy or controversial changes should go in as PRs. Or changes from third parties.
> 
> Thoughts?

I think we should merge single-commit PRs and trivial PRs manually, to keep linear history. However merging a well formatted feature PR (i.e. clicking the Github merge button) is totally ok (given a correct branch name).

About the branching model, we might want to keep only the master branch, and eventually one branch per release where fixes can be cherry-picked to. That would avoid merges from/to a dev branch. I'm comparing a few projects at the moment to see what will fit mstpd most.

**Comment by dvitas** [comment]
Good, let's go with the manual merge model for a while, we'll see how it works.

Any comments on the PR itself?

**Comment by commodo** [comment]
ack from me for this PR/change

regarding workflow model(s): I'm fine with whichever is decided :)
i usually don't have strong preference for this
i've seen Github projects use PRs used for single commits, so it's not uncommon;

Github's PR model makes git history a bit messy.
Would be nice if they would implement some patch-application model for small commits like this.

**Comment by vivien** [comment]
> Good, let's go with the manual merge model for a while, we'll see how it works.

Perfect. I usually prefer not to have merge commit *unless* it is relevant, i.e. grouping several commits adding a new feature, for the simple reason that a merge commit can be reverted. If several commits are not logically dependent and can be reverted individually, there is no need to merge them with `--no-ff`, à la Github. (It is just my opinion here, feel free to criticize)

> Github's PR model makes git history a bit messy.
> Would be nice if they would implement some patch-application model for small commits like this.

True. I've seen they added the setting to support `git merge --squash`. I don't see why they don't add such support for `--ff-only`, which would prevent a branch from being merged if it isn't up-to-date with master... Anyway :)

Thanks Vitalii for the commit, I've pushed it manually with a small reword to respect [commit keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) and the Git preference for a second empty line.

Closing this issue.

**Pull request closed without merging**
